// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: apps/pbstock/search_stock_plan_list.proto

package pbstock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchStockPlanListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pageno int64 `protobuf:"varint,1,opt,name=pageno,proto3" json:"pageno,omitempty"`
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Stock Code
	StockCode string `protobuf:"bytes,3,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
}

func (x *SearchStockPlanListRequest) Reset() {
	*x = SearchStockPlanListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStockPlanListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStockPlanListRequest) ProtoMessage() {}

func (x *SearchStockPlanListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStockPlanListRequest.ProtoReflect.Descriptor instead.
func (*SearchStockPlanListRequest) Descriptor() ([]byte, []int) {
	return file_apps_pbstock_search_stock_plan_list_proto_rawDescGZIP(), []int{0}
}

func (x *SearchStockPlanListRequest) GetPageno() int64 {
	if x != nil {
		return x.Pageno
	}
	return 0
}

func (x *SearchStockPlanListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchStockPlanListRequest) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

type SearchStockPlanListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int64                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pageno int64                    `protobuf:"varint,2,opt,name=pageno,proto3" json:"pageno,omitempty"`
	Count  int64                    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	List   []*SearchStockPlanDetail `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SearchStockPlanListResponse) Reset() {
	*x = SearchStockPlanListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStockPlanListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStockPlanListResponse) ProtoMessage() {}

func (x *SearchStockPlanListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStockPlanListResponse.ProtoReflect.Descriptor instead.
func (*SearchStockPlanListResponse) Descriptor() ([]byte, []int) {
	return file_apps_pbstock_search_stock_plan_list_proto_rawDescGZIP(), []int{1}
}

func (x *SearchStockPlanListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchStockPlanListResponse) GetPageno() int64 {
	if x != nil {
		return x.Pageno
	}
	return 0
}

func (x *SearchStockPlanListResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchStockPlanListResponse) GetList() []*SearchStockPlanDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type SearchStockPlanDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockCode      string  `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	FallPercent    string  `protobuf:"bytes,2,opt,name=fall_percent,json=fallPercent,proto3" json:"fall_percent,omitempty"`
	BuyPrice       float64 `protobuf:"fixed64,3,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	BuyQuantity    int64   `protobuf:"varint,4,opt,name=buy_quantity,json=buyQuantity,proto3" json:"buy_quantity,omitempty"`
	ProfitPercent  string  `protobuf:"bytes,5,opt,name=profit_percent,json=profitPercent,proto3" json:"profit_percent,omitempty"`
	SellPrice      float64 `protobuf:"fixed64,6,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	PlanMoney      int64   `protobuf:"varint,7,opt,name=plan_money,json=planMoney,proto3" json:"plan_money,omitempty"`
	ActualMoney    float64 `protobuf:"fixed64,8,opt,name=actual_money,json=actualMoney,proto3" json:"actual_money,omitempty"`
	QuickBuyQty    int64   `protobuf:"varint,9,opt,name=quick_buy_qty,json=quickBuyQty,proto3" json:"quick_buy_qty,omitempty"`
	QuickSellPrice float64 `protobuf:"fixed64,10,opt,name=quick_sell_price,json=quickSellPrice,proto3" json:"quick_sell_price,omitempty"`
}

func (x *SearchStockPlanDetail) Reset() {
	*x = SearchStockPlanDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchStockPlanDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStockPlanDetail) ProtoMessage() {}

func (x *SearchStockPlanDetail) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pbstock_search_stock_plan_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStockPlanDetail.ProtoReflect.Descriptor instead.
func (*SearchStockPlanDetail) Descriptor() ([]byte, []int) {
	return file_apps_pbstock_search_stock_plan_list_proto_rawDescGZIP(), []int{2}
}

func (x *SearchStockPlanDetail) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *SearchStockPlanDetail) GetFallPercent() string {
	if x != nil {
		return x.FallPercent
	}
	return ""
}

func (x *SearchStockPlanDetail) GetBuyPrice() float64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *SearchStockPlanDetail) GetBuyQuantity() int64 {
	if x != nil {
		return x.BuyQuantity
	}
	return 0
}

func (x *SearchStockPlanDetail) GetProfitPercent() string {
	if x != nil {
		return x.ProfitPercent
	}
	return ""
}

func (x *SearchStockPlanDetail) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *SearchStockPlanDetail) GetPlanMoney() int64 {
	if x != nil {
		return x.PlanMoney
	}
	return 0
}

func (x *SearchStockPlanDetail) GetActualMoney() float64 {
	if x != nil {
		return x.ActualMoney
	}
	return 0
}

func (x *SearchStockPlanDetail) GetQuickBuyQty() int64 {
	if x != nil {
		return x.QuickBuyQty
	}
	return 0
}

func (x *SearchStockPlanDetail) GetQuickSellPrice() float64 {
	if x != nil {
		return x.QuickSellPrice
	}
	return 0
}

var File_apps_pbstock_search_stock_plan_list_proto protoreflect.FileDescriptor

var file_apps_pbstock_search_stock_plan_list_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x6e,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x22, 0x69, 0x0a, 0x1a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x95, 0x01, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50,
	0x6c, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xef, 0x02, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x61, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62, 0x75, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x62, 0x75, 0x79, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x62, 0x75, 0x79, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x5f, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x6c, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x73, 0x65, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x6c, 0x61, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x71,
	0x75, 0x69, 0x63, 0x6b, 0x5f, 0x62, 0x75, 0x79, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x42, 0x75, 0x79, 0x51, 0x74, 0x79, 0x12,
	0x28, 0x0a, 0x10, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x71, 0x75, 0x69, 0x63, 0x6b,
	0x53, 0x65, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x70,
	0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_pbstock_search_stock_plan_list_proto_rawDescOnce sync.Once
	file_apps_pbstock_search_stock_plan_list_proto_rawDescData = file_apps_pbstock_search_stock_plan_list_proto_rawDesc
)

func file_apps_pbstock_search_stock_plan_list_proto_rawDescGZIP() []byte {
	file_apps_pbstock_search_stock_plan_list_proto_rawDescOnce.Do(func() {
		file_apps_pbstock_search_stock_plan_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pbstock_search_stock_plan_list_proto_rawDescData)
	})
	return file_apps_pbstock_search_stock_plan_list_proto_rawDescData
}

var file_apps_pbstock_search_stock_plan_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_pbstock_search_stock_plan_list_proto_goTypes = []interface{}{
	(*SearchStockPlanListRequest)(nil),  // 0: pbstock.SearchStockPlanListRequest
	(*SearchStockPlanListResponse)(nil), // 1: pbstock.SearchStockPlanListResponse
	(*SearchStockPlanDetail)(nil),       // 2: pbstock.SearchStockPlanDetail
}
var file_apps_pbstock_search_stock_plan_list_proto_depIdxs = []int32{
	2, // 0: pbstock.SearchStockPlanListResponse.list:type_name -> pbstock.SearchStockPlanDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_pbstock_search_stock_plan_list_proto_init() }
func file_apps_pbstock_search_stock_plan_list_proto_init() {
	if File_apps_pbstock_search_stock_plan_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_pbstock_search_stock_plan_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStockPlanListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pbstock_search_stock_plan_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStockPlanListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pbstock_search_stock_plan_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchStockPlanDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pbstock_search_stock_plan_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_pbstock_search_stock_plan_list_proto_goTypes,
		DependencyIndexes: file_apps_pbstock_search_stock_plan_list_proto_depIdxs,
		MessageInfos:      file_apps_pbstock_search_stock_plan_list_proto_msgTypes,
	}.Build()
	File_apps_pbstock_search_stock_plan_list_proto = out.File
	file_apps_pbstock_search_stock_plan_list_proto_rawDesc = nil
	file_apps_pbstock_search_stock_plan_list_proto_goTypes = nil
	file_apps_pbstock_search_stock_plan_list_proto_depIdxs = nil
}
